### ISSUE TITLE
probably user error

### ISSUE THREAD

**Issue by namurdock** [rzulian/lutron_custom_component#1]
First thing I'll say is this is probably user error, I never have much luck with custom components.

I am running HASSIO (0.115.6) and have dropped the content of your repo into the custom_components folder in a subfolder named lutron_custom.

When HASSIO boots i get the following:

```
Logger: homeassistant.setup

Source: custom_components/lutron_custom/__init__.py:57
First occurred: 8:50:03 PM (1 occurrences)
Last logged: 8:50:03 PM

Error during setup of component lutron_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/lutron_custom/__init__.py", line 57, in setup
    config[CONF_HOST], config[CONF_USERNAME], config[CONF_PASSWORD]
TypeError: 'NoneType' object is not subscriptable
```

config:

```
#Lutron
lutron_custom:
  host: 192.168.1.80
  username: <USERNAME>
  password: <PASSWORD>
  db_file: 'Lutron.xml'
```

**Comment by rzulian** [comment]
@namurdock :the domain is `lutron`
so it should be 
```
#Lutron
lutron:
  host: 192.168.1.80
  username: <USERNAME>
  password: <PASSWORD>
  db_file: 'Lutron.xml'
```

**Comment by namurdock** [comment]
Ah ok, should the folder in custom_components also be lutron or does that not matter?

**Comment by txwindsurfer** [comment]
@namurdock I have the folder in custom_compontents named lutron and my installation works.

**Comment by namurdock** [comment]
Yep, that did the job. Thank you!

**Comment by OlofBailey** [comment]
Sorry if this is a stupid question but I get the following. 

I've uploaded your repo to /homeassistant/custom_components/lutron and I've added the following to configuration.yaml

#Lutron
lutron:
  host: 192.168.1.42
  username: User4
  password: Lutron
  db_file: 'Lutron.xml'


====

Logger: homeassistant.setup
Source: setup.py:416
First occurred: 11:42:36 AM (1 occurrences)
Last logged: 11:42:36 AM

Error during setup of component lutron
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lutron/__init__.py", line 64, in setup
    hass.data[LUTRON_CONTROLLER].load_xml_db(db_file)
  File "/usr/local/lib/python3.12/site-packages/pylutron/__init__.py", line 615, in load_xml_db
    assert(parser.parse())     # throw our own exception
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pylutron/__init__.py", line 248, in parse
    root = ET.fromstring(self._xml_db_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 1335, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 3, column 23

**Comment by rzulian** [comment]
In the config dir you should have a file Lutron.xml. Can you check or post this file?
Also the standard configuration is 
lutron:
  host: 192.168.1.2
  username: lutron
  password: integration
  db_file: "Lutron.xml"
The username and password are different from yours. Can you check this also?

**Comment by OlofBailey** [comment]
@rzulian thank you so much for your work on this and response. So incredibly appreciated.

I have added the following to /homeassistant/configuration.yaml

```
# Loads default set of integrations. Do not remove.
default_config:

lutron:
  host: 192.168.1.42
  username: User4
  password: Lutron
  db_file: "Lutron.xml"

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```

I've not been able to find a Lutron.xml or /config directory. Where should this be? 

2024-09-10 12:58:39.580 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration lutron which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-10 12:58:42.808 ERROR (MainThread) [homeassistant.setup] Error during setup of component lutron
File "/config/custom_components/lutron/__init__.py", line 64, in setup
hass.data[LUTRON_CONTROLLER].load_xml_db(db_file)
File "/usr/local/lib/python3.12/site-packages/pylutron/__init__.py", line 615, in load_xml_db
File "/usr/local/lib/python3.12/site-packages/pylutron/__init__.py", line 248, in parse
