### ISSUE TITLE
What is the complete configuration ?

### ISSUE THREAD

**Issue by vincegre** [rzulian/lutron_custom_component#6]
Hi

I'm trying to use the custom component in my system but I'm confused by explanations about configuration. I have copied files of custom components in my custom_components directory but where do I put the config:

  host: 192.168.1.23
  username: lutron
  password: password
  db_file: 'Lutron.xml'

as in configuration.yaml it doesn't work like that :(

Thanks for clarifications,

Vincèn

**Comment by rzulian** [comment]
Hi,
You need to copy the code into ` /config/custom_components/lutron`.
Then add this to your `configuration.yaml`:
```
lutron:
  host: 192.168.1.2
  username: lutron
  password: integration
  db_file: "Lutron.xml"
```
